/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.io.File;
import java.io.IOException;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Server-EWS
 */
public class FrmDocumentos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmDocumentos
     */
    public FrmDocumentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cPresentacion = new javax.swing.JButton();
        cCompromiso = new javax.swing.JButton();
        cAceptacion = new javax.swing.JButton();
        cSolicitudServicio = new javax.swing.JButton();
        cAsignacion = new javax.swing.JButton();
        solicitudPrestante = new javax.swing.JButton();
        descargarTodos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Documentacion para Servicio Social");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/consultas.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        cPresentacion.setText("Carta de Presentacion");
        cPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPresentacionActionPerformed(evt);
            }
        });

        cCompromiso.setText("Carta Compromiso");
        cCompromiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCompromisoActionPerformed(evt);
            }
        });

        cAceptacion.setText("Carta Aceptacion");

        cSolicitudServicio.setText("Solicitud de Servicio");
        cSolicitudServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSolicitudServicioActionPerformed(evt);
            }
        });

        cAsignacion.setText("Carta de Asignacion");
        cAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAsignacionActionPerformed(evt);
            }
        });

        solicitudPrestante.setText("Solicitud de Prestante");
        solicitudPrestante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudPrestanteActionPerformed(evt);
            }
        });

        descargarTodos.setText("Descargar Todos");
        descargarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descargarTodosActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cSolicitudServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cCompromiso, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cAceptacion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(solicitudPrestante, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(descargarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cPresentacion)
                    .addComponent(cCompromiso)
                    .addComponent(cAceptacion))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cSolicitudServicio)
                    .addComponent(cAsignacion)
                    .addComponent(solicitudPrestante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descargarTodos)
                    .addComponent(btnSalir))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPresentacionActionPerformed
    
    }//GEN-LAST:event_cPresentacionActionPerformed

    private void cCompromisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCompromisoActionPerformed
        JFileChooser fileChooser=new JFileChooser();
    File file = new File("CARTA COMPROMISO.docx");
    fileChooser.setSelectedFile(file);
    if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
    file = fileChooser.getSelectedFile();
    System.out.println(file.toString());
    File documento=new File("C:\\SocialServiceSystem\\ArchivosSS\\CARTA COMPROMISO.docx");
        try {
            copiarArchivo(documento.toString(),file.toString());
        } catch (IOException ex) {
            Logger.getLogger(FrmDocumentos.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    }//GEN-LAST:event_cCompromisoActionPerformed

    private void cSolicitudServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSolicitudServicioActionPerformed
       JFileChooser fileChooser=new JFileChooser();
    File file = new File("SOLICITUD DE SERVICIO SOCIAL.doc");
    fileChooser.setSelectedFile(file);
    if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
    file = fileChooser.getSelectedFile();
    System.out.println(file.toString());
    File documento=new File("C:\\SocialServiceSystem\\ArchivosSS\\SOLICITUD DE SERVICIO SOCIAL.doc");
        try {
            copiarArchivo(documento.toString(),file.toString());
        } catch (IOException ex) {
            Logger.getLogger(FrmDocumentos.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    }//GEN-LAST:event_cSolicitudServicioActionPerformed

    private void cAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAsignacionActionPerformed
    
     JFileChooser fileChooser=new JFileChooser();
    File file = new File("CARTA DE ASIGNACION.doc");
    fileChooser.setSelectedFile(file);
    if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
    file = fileChooser.getSelectedFile();
    System.out.println(file.toString());
    File documento=new File("C:\\SocialServiceSystem\\ArchivosSS\\CARTA DE ASIGNACION.doc");
        try {
            copiarArchivo(documento.toString(),file.toString());
        } catch (IOException ex) {
            Logger.getLogger(FrmDocumentos.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    }//GEN-LAST:event_cAsignacionActionPerformed

    private void solicitudPrestanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudPrestanteActionPerformed
    JFileChooser fileChooser=new JFileChooser();
    File file = new File("SOLICITUD DE PRESTANTE.doc");
    fileChooser.setSelectedFile(file);
    if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
    file = fileChooser.getSelectedFile();
    System.out.println(file.toString());
    File documento=new File("C:\\SocialServiceSystem\\ArchivosSS\\SOLICITUD DE PRESTANTE.doc");
        try {
            copiarArchivo(documento.toString(),file.toString());
        } catch (IOException ex) {
            Logger.getLogger(FrmDocumentos.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    }//GEN-LAST:event_solicitudPrestanteActionPerformed

    private void descargarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descargarTodosActionPerformed
    JFileChooser fileChooser=new JFileChooser();
    File carpeta=new File("DOCUMENTOS SERVICIO SOCIAL");
    fileChooser.setSelectedFile(carpeta);
    if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
    carpeta = fileChooser.getSelectedFile();
    carpeta.mkdirs();
    String rutaCarpeta=carpeta.toString();
    //Ruta de los documentos a copiar
    File documento1=new File("C:\\SocialServiceSystem\\ArchivosSS\\CARTA COMPROMISO.docx");
    File documento2=new File("C:\\SocialServiceSystem\\ArchivosSS\\SOLICITUD DE SERVICIO SOCIAL.doc");
    File documento3=new File("C:\\SocialServiceSystem\\ArchivosSS\\CARTA DE ASIGNACION.doc");
    File documento4=new File("C:\\SocialServiceSystem\\ArchivosSS\\SOLICITUD DE PRESTANTE.doc");
    //Ruta final de los archivos
    String ruta1=rutaCarpeta+"\\CARTA COMPROMISO.docx";
    String ruta2=rutaCarpeta+"\\SOLICITUD DE SERVICIO SOCIAL.doc";
    String ruta3=rutaCarpeta+"\\CARTA DE ASIGNACION.doc";
    String ruta4=rutaCarpeta+"\\SOLICITUD DE PRESTANTE.doc"; 
    
    try {
            copiarArchivo(documento1.toString(),ruta1);
            copiarArchivo(documento2.toString(),ruta2);
            copiarArchivo(documento3.toString(),ruta3);
            copiarArchivo(documento4.toString(),ruta4);
            
        } catch (IOException ex) {
            Logger.getLogger(FrmDocumentos.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
    }//GEN-LAST:event_descargarTodosActionPerformed

     public void copiarArchivo(String origen, String destino) throws IOException {
        Path FROM = Paths.get(origen);
        Path TO = Paths.get(destino);
        //sobreescribir el fichero de destino, si existe, y copiar
        // los atributos, incluyendo los permisos rwx
        CopyOption[] options = new CopyOption[]{
          StandardCopyOption.REPLACE_EXISTING,
          StandardCopyOption.COPY_ATTRIBUTES
        }; 
        Files.copy(FROM, TO, options);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton cAceptacion;
    private javax.swing.JButton cAsignacion;
    private javax.swing.JButton cCompromiso;
    private javax.swing.JButton cPresentacion;
    private javax.swing.JButton cSolicitudServicio;
    private javax.swing.JButton descargarTodos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton solicitudPrestante;
    // End of variables declaration//GEN-END:variables
}
